version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "monthly"
  rebase-strategy: "disabled"
- package-ecosystem: "cargo"
  directory: "/test-utils/"
  schedule:
    interval: "monthly"
  rebase-strategy: "disabled"
